// GENERATED by `node scripts/authors/build-index.mjs` — one explicit import per author file, so a bundler sees every file.
// `src/lib/reference-authors.test.ts` fails if a JSON file in this directory is missing here.
import type { ReferenceAuthor } from "@/lib/reference-authors";

import a_ann_bannon from "./ann-bannon.json";
import a_edgar_allan_poe from "./edgar-allan-poe.json";
import a_emma_donoghue from "./emma-donoghue.json";
import a_h_j_r_murray from "./h-j-r-murray.json";
import a_hans_christian_andersen from "./hans-christian-andersen.json";
import a_henry_dudeney from "./henry-dudeney.json";
import a_henry_lee from "./henry-lee.json";
import a_ian_livingstone from "./ian-livingstone.json";
import a_jeanette_winterson from "./jeanette-winterson.json";
import a_karin_kallmaker from "./karin-kallmaker.json";
import a_katherine_v_forrest from "./katherine-v-forrest.json";
import a_lafcadio_hearn from "./lafcadio-hearn.json";
import a_malinda_lo from "./malinda-lo.json";
import a_marcus_aurelius from "./marcus-aurelius.json";
import a_martin_gardner from "./martin-gardner.json";
import a_mary_shelley from "./mary-shelley.json";
import a_nicola_griffith from "./nicola-griffith.json";
import a_oscar_wilde from "./oscar-wilde.json";
import a_ovid from "./ovid.json";
import a_patricia_highsmith from "./patricia-highsmith.json";
import a_radclyffe from "./radclyffe.json";
import a_sabine_baring_gould from "./sabine-baring-gould.json";
import a_sam_loyd from "./sam-loyd.json";
import a_sarah_waters from "./sarah-waters.json";
import a_t_h_thomas from "./t-h-thomas.json";
import a_thomas_keightley from "./thomas-keightley.json";
import a_virginia_woolf from "./virginia-woolf.json";
import a_wirt_sikes from "./wirt-sikes.json";

/** Every researched author, A to Z by slug. Validated by `reference-authors.test.ts` and `scripts/authors/verify-sources.mjs`. */
export const REFERENCE_AUTHOR_DATA = [a_ann_bannon, a_edgar_allan_poe, a_emma_donoghue, a_h_j_r_murray, a_hans_christian_andersen, a_henry_dudeney, a_henry_lee, a_ian_livingstone, a_jeanette_winterson, a_karin_kallmaker, a_katherine_v_forrest, a_lafcadio_hearn, a_malinda_lo, a_marcus_aurelius, a_martin_gardner, a_mary_shelley, a_nicola_griffith, a_oscar_wilde, a_ovid, a_patricia_highsmith, a_radclyffe, a_sabine_baring_gould, a_sam_loyd, a_sarah_waters, a_t_h_thomas, a_thomas_keightley, a_virginia_woolf, a_wirt_sikes] as unknown as ReferenceAuthor[];
