#!/usr/bin/env node
/** Rewrite src/content/authors/index.ts from the JSON files in that directory (one explicit import each). */
import { readdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const DIR = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../../src/content/authors");
const files = readdirSync(DIR).filter((f) => f.endsWith(".json")).map((f) => f.replace(/\.json$/, "")).sort();
const ident = (f) => `a_${f.replace(/-/g, "_")}`;
const out = [
  "// GENERATED by `node scripts/authors/build-index.mjs` — one explicit import per author file, so a bundler sees every file.",
  "// `src/lib/reference-authors.test.ts` fails if a JSON file in this directory is missing here.",
  'import type { ReferenceAuthor } from "@/lib/reference-authors";',
  "",
  ...files.map((f) => `import ${ident(f)} from "./${f}.json";`),
  "",
  "/** Every researched author, A to Z by slug. Validated by `reference-authors.test.ts` and `scripts/authors/verify-sources.mjs`. */",
  `export const REFERENCE_AUTHOR_DATA = [${files.map(ident).join(", ")}] as unknown as ReferenceAuthor[];`,
  "",
].join("\n");
writeFileSync(path.join(DIR, "index.ts"), out);
console.log(`index.ts: ${files.length} authors`);
