#!/usr/bin/env node
/**
 * Write AUDIT/AUTHOR-DIRECTORY-SOURCES.md from the data itself — so the report cannot say anything the data does not.
 *
 *   node scripts/authors/report.mjs
 */
import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { AUTHORS, BOOKS } from "../catalog/valice-catalog.mjs";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../..");
const DIR = path.join(ROOT, "src/content/authors");
const authors = readdirSync(DIR).filter((f) => f.endsWith(".json")).map((f) => JSON.parse(readFileSync(path.join(DIR, f), "utf8")));
const verification = JSON.parse(readFileSync(path.join(ROOT, "data/authors/verification.json"), "utf8"));
const published = new Set(AUTHORS.filter((a) => BOOKS.some((b) => b.websiteStatus === "published" && b.authors.includes(a.slug))).map((a) => a.slug));
const LABEL = { historical: "Historical voices", "game-puzzle": "Games & puzzles", "sapphic-romance": "Sapphic romance" };
const host = (u) => ({ "en.wikipedia.org": "Wikipedia", "en.wikisource.org": "Wikisource", "www.wikidata.org": "Wikidata", "id.loc.gov": "Library of Congress" }[new URL(u).host] ?? new URL(u).host);

const byCat = (c) => authors.filter((a) => a.category === c).sort((a, b) => a.name.localeCompare(b.name));
const withPortrait = authors.filter((a) => a.portrait);
const licences = {};
for (const a of withPortrait) licences[a.portrait.licence] = (licences[a.portrait.licence] ?? 0) + 1;
const gathered = Object.values(verification.authors).map((v) => v.gatheredAt).sort()[0]?.slice(0, 10);

let md = `# Authors directory — sources and photograph licences

*Generated by \`node scripts/authors/report.mjs\` from \`src/content/authors/*.json\` and \`data/authors/verification.json\`. Do not edit by hand.*

## What is on the page

${authors.length} researched authors: ${byCat("historical").length} historical voices, ${byCat("game-puzzle").length} makers of games and puzzles, ${byCat("sapphic-romance").length} novelists of sapphic and lesbian romance. ${[...published].filter((s) => authors.some((a) => a.slug === s)).length} of them are also on the Valice list (an edition of their public-domain work is published here); the other ${authors.length - [...published].filter((s) => authors.some((a) => a.slug === s)).length} are **reference authors**, shown for the reading context around the shelf, and every page says in plain words that Valice Press has no connection with them.

Three authors Valice publishes who are not researched here — Emre Doğan, Harper Hayes and Quinn Gallagher — have pages built only from the catalogue's approved biographies and their books; nothing about them is taken from outside.

## How each fact was checked

\`scripts/authors/verify-sources.mjs\` fetches every listed source and fails unless: the source answers 200 and names the person; the **birth and death years agree across Wikidata and the Library of Congress authority record** (two independent compilations); every year in the works and timeline appears in the sources' text; and each key claim (an award, an epithet, a title) appears there word for word. Last full run: **${gathered}**, ${Object.values(verification.authors).filter((v) => v.ok).length}/${Object.keys(verification.authors).length} authors passing.

Where two sources disagree it is written down on the person's page (A note on the dates) and in the data: ${authors.filter((a) => a.dateDiscrepancy).map((a) => `**${a.name}** — ${a.dateDiscrepancy}`).join(" ")}

## Photographs

${withPortrait.length} of ${authors.length} have a photograph (or, for ancient and some Victorian subjects, a painting or a bust); the rest show an initials mark and say so. Every file is from Wikimedia Commons, passed a licence allowlist (public domain, CC0, CC BY, CC BY-SA — nothing NonCommercial, nothing with a Commons restriction flag), was decoded and re-encoded by us at 3:4 and never enlarged, and carries its credit line, licence, source URL, the source file's SHA-1 and the published file's SHA-256 in its JSON.

Licences: ${Object.entries(licences).sort((a, b) => b[1] - a[1]).map(([l, n]) => `${l} × ${n}`).join(", ")}.

Refused: Malinda Lo's only free photograph (Commons flags personality rights). No free photograph found for ${authors.filter((a) => !a.portrait && a.slug !== "malinda-lo").map((a) => a.name).join(", ")}.

`;

for (const c of ["historical", "game-puzzle", "sapphic-romance"]) {
  md += `## ${LABEL[c]}\n\n`;
  for (const a of byCat(c)) {
    md += `### ${a.name} (${a.years})${published.has(a.slug) ? " — on the Valice list" : ""}\n\n`;
    md += a.sources.map((s) => `- [${s.label}](${s.url}) · ${host(s.url)}`).join("\n") + "\n";
    if (a.portrait) md += `- Photograph: \`${a.portrait.sourceFile}\` — ${a.portrait.credit} — [${a.portrait.licence}](${a.portrait.licenceUrl ?? a.portrait.sourceUrl}) — [Commons page](${a.portrait.sourceUrl})\n`;
    else md += `- Photograph: none — ${a.portraitNote}\n`;
    md += "\n";
  }
}
writeFileSync(path.join(ROOT, "AUDIT/AUTHOR-DIRECTORY-SOURCES.md"), md);
console.log(`AUDIT/AUTHOR-DIRECTORY-SOURCES.md — ${md.length} chars, ${authors.length} authors`);
